service: findme-microservices

frameworkVersion: "3"

custom:
  localstack:
    stages:
      - local
      - dev
    host: ${self:custom.stage.${opt:stage}.host}
    edgePort: 4566
    lambda:
      mountCode: false
  pythonRequirements:
    dockerizePip: non-linux
  stage:
    dev:
      host: http://localstack-main
      frontendOrigin: http://localhost:8100
    local:
      host: http://localhost
      frontendOrigin: http://localhost:8100

package:
  individually: true

provider:
  name: aws
  runtime: python3.9
  region: eu-central-2
  apiGateway:
    restApiId:
      "Fn::ImportValue": findmeApiGateway-restApiId
    restApiRootResourceId:
      "Fn::ImportValue": findmeApiGateway-rootResourceId

functions:
  findme-users:
    handler: handler.lambda_handler
    module: findme-users
    environment:
      FRONTEND_ORIGIN: ${self:custom.stage.${opt:stage}.frontendOrigin}
    events:
      - http:
          path: /users/{id}
          method: get
          cors:
            origin: ${self:custom.stage.${opt:stage}.frontendOrigin}
          request:
            parameters:
              paths:
                id: true
      - http:
          path: /users
          method: post
          cors:
            origin: ${self:custom.stage.${opt:stage}.frontendOrigin}

resources: # CloudFormation template syntax from here on.
  Resources:
    usersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: usersTable
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: N
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

plugins:
  - serverless-python-requirements
  - serverless-localstack
