service: aws-custom-authorizer-auth0

frameworkVersion: "3"

custom:
  localstack:
    stages:
      - local
    lambda:
      mountCode: false
  pythonRequirements:
    dockerizePip: non-linux

package:
  individually: true

provider:
  name: aws
  runtime: python3.9
  region: eu-central-2


functions:
  findme-users:
    handler: handler.lambda_handler
    module: findme-users
    events:
      - http:
          path: /
          method: get
          cors: true
      - http:
          path: /users
          method: post
          cors: true

resources: # CloudFormation template syntax from here on.
      Resources:
        usersTable:
          Type: AWS::DynamoDB::Table
          Properties:
            TableName: usersTable
            AttributeDefinitions:
              - AttributeName: username
                AttributeType: S
            KeySchema:
              - AttributeName: username
                KeyType: HASH
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1

plugins:
  - serverless-python-requirements
  - serverless-localstack

